-- MySQL Script generated by MySQL Workbench
-- Fri Apr  4 20:22:10 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_at1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_at1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_at1`;
CREATE SCHEMA IF NOT EXISTS `bd_at1` DEFAULT CHARACTER SET utf8 ;
USE `bd_at1` ;

-- -----------------------------------------------------
-- Table `bd_at1`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_at1`.`Medico` (
  `idMedico` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `especialidade` VARCHAR(45) NOT NULL,
  `CRM` INT NOT NULL,
  `dddTelefone` INT NOT NULL,
  `Telofone` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `data_cadastro` DATE NOT NULL,
  PRIMARY KEY (`idMedico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_at1`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_at1`.`Paciente` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `data_nascimeto` DATE NOT NULL,
  `sexo` VARCHAR(20) NOT NULL,
  `ddd Telefone` INT NOT NULL,
  `telefone contato Paciente` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(150) NOT NULL,
  `cep` INT NOT NULL,
  `logradouro` CHAR(20) NOT NULL,
  `numero` INT NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` CHAR(11) NOT NULL,
  `data_cadastro` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_at1`.`Consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_at1`.`Consulta` (
  `id` INT NOT NULL,
  `idPaciente` INT NOT NULL,
  `idMedico` INT NOT NULL,
  `data_consulta` DATETIME NOT NULL,
  `descricao` VARCHAR(150) NOT NULL,
  `status` CHAR(20) NOT NULL,
  PRIMARY KEY (`id`),

  CONSTRAINT `fk_Consulta_Medico`
    FOREIGN KEY (`idMedico`)
    REFERENCES `bd_at1`.`Medico` (`idMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consulta_Paciente`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `bd_at1`.`Paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



INSERT INTO `Medico`(`idmedico`,`nome`,`especialidade`,`CRM`,`dddTelefone`,`Telefone`,`email`,`data_cadastro`)
VALUES('1','jorge martins','clinico','456123','11','995665126','jorge_martins@danielsalla.com.br','2025-04-02');

INSERT INTO `Medico`(`idmedico`,`nome`,`especialidade`,`CRM`,`dddTelefone`,`Telefone`,`email`,`data_cadastro`)
VALUES('2','César Iago Rocha','ontorrino','200011','14','995665126','cesar-rocha96@digen.com.br','2025-05-09');

INSERT INTO `Medico`(`idmedico`,`nome`,`especialidade`,`CRM`,`dddTelefone`,`Telefone`,`email`,`data_cadastro`)
VALUES('3','Thomas Thiago Manoel Viana','clinico','456123','55','939207265','thomas_viana@iaru.com.br','2025-08-12');

INSERT INTO `Medico`(`idmedico`,`nome`,`especialidade`,`CRM`,`dddTelefone`,`Telefone`,`email`,`data_cadastro`)
VALUES('4','"Bryan Noah Isaac Brito','raio-x','789562','75','996716858','bryannoahbrito@brunofaria.com','2025-07-22');

INSERT INTO `Medico`(`idmedico`,`nome`,`especialidade`,`CRM`,`dddTelefone`,`Telefone`,`email`,`data_cadastro`)
VALUES('5','Benedita Luiza Juliana Melo','pediatra','456155','84','35127876','benedita_luiza_melo@associate.com.br','2025-01-07');



INSERT INTO `Paciente`(`id`,`nome`,`data nascimento`,`sexo`,`dddTelefone`,`Telefone`,`email`,`endereco`,`cep`,`logradouro`,`numero`,`bairro`,`cidade`,`estado`,`data_cadastro`)
VALUES('542674400269','Simone Marina Milena Nunes','04-03-2003','Feminino','71','7127914407','simone_marina_nunes@ssala.com.br','Rua Ivonildes Seabra','64017830','casa','795','Três Andares','Teresina','PI','2025-08-01');

INSERT INTO `Paciente`(`id`,`nome`,`data nascimento`,`sexo`,`dddTelefone`,`Telefone`,`email`,`endereco`,`cep`,`logradouro`,`numero`,`bairro`,`cidade`,`estado`,`data_cadastro`)
VALUES('76619231306','Malu Luna Marcela da Rocha','25-02-1949','Feminino','79','27530583','malu_luna_darocha@ctfmgacc.org.br','Rua Pedro Teixeira Guimarães','49048290','casa','509','Luzia','Aracaju','SE','2025-08-20');

INSERT INTO `Paciente`(`id`,`nome`,`data nascimento`,`sexo`,`dddTelefone`,`Telefone`,`email`,`endereco`,`cep`,`logradouro`,`numero`,`bairro`,`cidade`,`estado`,`data_cadastro`)
VALUES('87186641725",','Samuel Raul Giovanni Olive','02-01-1995','Masculino','68','27317217','samuel.raul.oliveira@uol.om.br','Travessa Máncio Nilia','69901658','casa','506','Conjunto Oscar Passos','Rio Branco','AC','2025-08-11');

INSERT INTO `Paciente`(`id`,`nome`,`data nascimento`,`sexo`,`dddTelefone`,`Telefone`,`email`,`endereco`,`cep`,`logradouro`,`numero`,`bairro`,`cidade`,`estado`,`data_cadastro`)
VALUES('90594805384','Vitor Carlos Pereira','04-03-2003','Masculino','81','35845635','vitor.carlos.pereira@uninorte.com.br','Rua Itapejara','54730790','condominio','790','Rua Itapejara','Pixete','PE','2025-08-10');

INSERT INTO `Paciente`(`id`,`nome`,`data nascimento`,`sexo`,`dddTelefone`,`Telefone`,`email`,`endereco`,`cep`,`logradouro`,`numero`,`bairro`,`cidade`,`estado`,`data_cadastro`)
VALUES('01270915215','Calebe Tomás Cláudio Gomes','07-03-1963','Masculino','81','37906926','calebetomasgomes@pq.cnpq.br','Rua Pocinho','52081025','casa','556','Vasco da Gama','Recife','PE','2025-08-09');