-- MySQL Script generated by MySQL Workbench
-- Thu Apr  3 21:09:27 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_Seguradora
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_Seguradora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_Seguradora` DEFAULT CHARACTER SET utf8 ;
USE `bd_Seguradora` ;

-- -----------------------------------------------------
-- Table `bd_Seguradora`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Seguradora`.`Cliente` (
  `numero` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` INT NOT NULL,
  `fone` INT NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(20) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_Seguradora`.`Apolice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Seguradora`.`Apolice` (
  `numero` INT NOT NULL,
  `numerodoCliente` INT NOT NULL,
  `numeroApolice` INT NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`numero`),
  
  CONSTRAINT `fk_Cliente_apolice`
    FOREIGN KEY (`numerodoCliente`)
    REFERENCES `bd_Seguradora`.`Cliente` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_Seguradora`.`Carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Seguradora`.`Carro` (
  `registro` INT NOT NULL,
  `numeroApolice` INT NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Cor` VARCHAR(20) NOT NULL,
  `Km` DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (`registro`),
 
  CONSTRAINT `fk_Apolice_Carro`
    FOREIGN KEY (`numeroApolice`)
    REFERENCES `bd_Seguradora`.`Apolice` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_Seguradora`.`Acidentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Seguradora`.`Acidentes` (
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `local` VARCHAR(45) NOT NULL,
  `registro` INT NOT NULL,
  `numerodoCarro` INT NOT NULL,
  PRIMARY KEY (`data`, `hora`),
 
  CONSTRAINT `fk_Acidentes_Carro`
    FOREIGN KEY (`numerodoCarro`)
    REFERENCES `bd_Seguradora`.`Carro` (`registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `Cliente`(`numero`,`nome`,`cpf`,`fone`,`endereco`,`bairro`,`estado`)
VALUES('213','ireu pres','45678891221','1145632789','rua do abreu','jd onde','São Paulo');

INSERT INTO `Cliente`(`numero`,`nome`,`cpf`,`fone`,`endereco`,`bairro`,`estado`)
VALUES('720','joao da silva pres','45678894580','1145639929','rua como é','jd amigo','São Paulo');

INSERT INTO `Cliente`(`numero`,`nome`,`cpf`,`fone`,`endereco`,`bairro`,`estado`)
VALUES('429','lima da costa pres','45678848026','7527025820','PraÃ§a JosÃ© Borges do Vale, ','jd um dia','Bahia');

INSERT INTO `Cliente`(`numero`,`nome`,`cpf`,`fone`,`endereco`,`bairro`,`estado`)
VALUES('563','pedro sei la','20313258647','7537161779','PraÃ§a JosÃ© Borges do Vale','Centro','Bahia');

INSERT INTO `Cliente`(`numero`,`nome`,`cpf`,`fone`,`endereco`,`bairro`,`estado`)
VALUES('852','FÃ¡bio Monteiro','45678907421','7535669729','Avenida Ministro Oliveira Brito','Icozeira','Bahia');


INSERT INTO `Apolice`(`numero`,`numerodoCliente`,`numeroApolice`,`valor`)
VALUES('2','5512457889','11',50.000);

INSERT INTO `Apolice`(`numero`,`numerodoCliente`,`numeroApolice`,`valor`)
VALUES('4','5512451062','12',45.000);

INSERT INTO `Apolice`(`numero`,`numerodoCliente`,`numeroApolice`,`valor`)
VALUES('6','5512457450','16',70.000);

INSERT INTO `Apolice`(`numero`,`numerodoCliente`,`numeroApolice`,`valor`)
VALUES('8','5512454111','18',25.000);

INSERT INTO `Apolice`(`numero`,`numerodoCliente`,`numeroApolice`,`valor`)
VALUES('10','5512455522','20',40.000);


INSERT INTO `Carro`(`registro`,`numeroApolice`,`marca`,`cor`,`km`)
VALUES('101','45','gol','preto','22.000');

INSERT INTO `Carro`(`registro`,`numeroApolice`,`marca`,`cor`,`km`)
VALUES('304','785','corola','prata','72.000');

INSERT INTO `Carro`(`registro`,`numeroApolice`,`marca`,`cor`,`km`)
VALUES('160','00','civic','vermelho','45.000');

INSERT INTO `Carro`(`registro`,`numeroApolice`,`marca`,`cor`,`km`)
VALUES('500','57','vectra','branco','62.000');

INSERT INTO `Carro`(`registro`,`numeroApolice`,`marca`,`cor`,`km`)
VALUES('245','68','siena','preto','122.000');


INSERT INTO `Acidentes`(`data`,`hora`,`local`,`registro`,`numerodocarro`)
VALUES('2024-07-06','15:00:01','rua do abreu','9','793');

INSERT INTO `Acidentes`(`data`,`hora`,`local`,`registro`,`numerodocarro`)
VALUES('2015-06-04','22:30:01','rua do esta la','7','450');

INSERT INTO `Acidentes`(`data`,`hora`,`local`,`registro`,`numerodocarro`)
VALUES('2022-09-28','10:10:01','rua do estafo','3','593');

INSERT INTO `Acidentes`(`data`,`hora`,`local`,`registro`,`numerodocarro`)
VALUES('2024-01-15','00:00:01','rua do vc que sabe','1','193');

INSERT INTO `Acidentes`(`data`,`hora`,`local`,`registro`,`numerodocarro`)
VALUES('2024-02-24','16:25:01','rua do entao ta','51','794');



