-- MySQL Script generated by MySQL Workbench
-- Wed Apr  2 21:09:20 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_Vendas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_Vendas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_Vendas` DEFAULT CHARACTER SET utf8 ;
USE `bd_Vendas` ;

-- -----------------------------------------------------
-- Table `bd_Vendas`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Vendas`.`Fornecedor` (
  `idFornecedor` INT NOT NULL AUTO_INCREMENT,
  `razaoSocial` VARCHAR(20) NOT NULL,
  `nomeFantasia` VARCHAR(20) NULL,
  `Telefone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idFornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_Vendas`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Vendas`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nomeProduto` VARCHAR(20) NOT NULL,
  `precoUnitario` DECIMAL(12,2) NOT NULL,
  `idFornecedor` INT NOT NULL,
  
  PRIMARY KEY (`idProduto`),
  CONSTRAINT `fk_Fornecedor_Produto`
    FOREIGN KEY (`idFornecedor`)
    REFERENCES `bd_Vendas`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_Vendas`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Vendas`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nomeCliente` VARCHAR(20) NOT NULL,
  `rua` VARCHAR(20) NOT NULL,
  `numero` INT NOT NULL,
  `fone` VARCHAR(20) NOT NULL,
  `bairro` VARCHAR(20) NOT NULL,
  `cidade` VARCHAR(20) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_Vendas`.`notaFiscal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Vendas`.`notaFiscal` (
  `numeroNota` INT NOT NULL AUTO_INCREMENT,
  `valorNota` DECIMAL(12,2) NOT NULL,
  `dataEmissao` DATE NOT NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`numeroNota`),
  
  CONSTRAINT `fk_Cliente_notaFiscal`
    FOREIGN KEY (`idCliente`)
    REFERENCES `bd_Vendas`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_Vendas`.`itemNota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Vendas`.`itemNota` (
  `idProduto` INT NOT NULL,
  `numeroNota` INT NOT NULL,
  `qtdeItem` INT NOT NULL,
  `valorItem` DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (`idProduto`, `numeroNota`),
  
  CONSTRAINT `fk_Produto_itemNota`
    FOREIGN KEY (`idProduto`)
    REFERENCES `bd_Vendas`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notaFiscal_itemNota`
    FOREIGN KEY (`numeroNota`)
    REFERENCES `bd_Vendas`.`notaFiscal` (`numeroNota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `fornecedor`(`idFornecedor`,`razaoSocial`,`nomeFantasia`,`Telefone`)
VALUES(10,'Fornecedor um','Forne1','1145561252');

INSERT INTO `fornecedor`(`idFornecedor`,`razaoSocial`,`nomeFantasia`,`Telefone`)
VALUES(22,'era uma vez','erumavez','1156895542');

INSERT INTO `fornecedor`(`idFornecedor`,`razaoSocial`,`nomeFantasia`,`Telefone`)
VALUES(7,'nascesuco','nasuco','115688520');

INSERT INTO `fornecedor`(`idFornecedor`,`razaoSocial`,`nomeFantasia`,`Telefone`)
VALUES(9,'uchiha','uch','1101023578');


INSERT INTO `cliente`(`idcliente`,`nomecliente`,`rua`,`numero`,`fone`.`bairro`,`cidade`,`estado`)
VALUES(2,'uchiha','rua dos uchihas bom',40,1155897812,'ja foi','São Paulo','SP');

INSERT INTO `cliente`(`idcliente`,`nomecliente`,`rua`,`numero`,`fone`.`bairro`,`cidade`,`estado`)
VALUES(15,'abreu','rua dos passaros',80,1123693641,'jd nação','São Paulo','SP');

INSERT INTO `cliente`(`idcliente`,`nomecliente`,`rua`,`numero`,`fone`.`bairro`,`cidade`,`estado`)
VALUES(15,'ze barro','rua dois dias',100,1115605798,'jd nao sei','São Paulo','SP');

INSERT INTO `cliente`(`idcliente`,`nomecliente`,`rua`,`numero`,`fone`.`bairro`,`cidade`,`estado`)
VALUES(15,'moscow','rua um dia',05,1151616038,'jd la','São Paulo','SP');



INSERT INTO `notafiscal`(`numeronota`,`valornota`,`dataemissao`,`idcliente`)
VALUES('65','55.55','2024-07-12','8123');

INSERT INTO `notafiscal`(`numeronota`,`valornota`,`dataemissao`,`idcliente`)
VALUES('75','55.54','2024-07-16','7893');

INSERT INTO `notafiscal`(`numeronota`,`valornota`,`dataemissao`,`idcliente`)
VALUES('45','56.01','2024-07-12','8743');

INSERT INTO `notafiscal`(`numeronota`,`valornota`,`dataemissao`,`idcliente`)
VALUES('26','49.55','2024-06-19','7256');




INSERT INTO `produto`(`idproduto`,`nomeproduto`,`precounitario`,`idfornecedor`)
VALUES('226','bacia','78.55','72566');

INSERT INTO `produto`(`idproduto`,`nomeproduto`,`precounitario`,`idfornecedor`)
VALUES('310','panela','99.02','72589');

INSERT INTO `produto`(`idproduto`,`nomeproduto`,`precounitario`,`idfornecedor`)
VALUES('581','arroz','26.55','750020');

INSERT INTO `produto`(`idproduto`,`nomeproduto`,`precounitario`,`idfornecedor`)
VALUES('461','ovo','31.99','745779');





INSERT INTO `itemnota`(`idproduto`,`numeronota`,`qdteitem`,`valoritem`)
VALUES('32','7','20','199.99');

INSERT INTO `itemnota`(`idproduto`,`numeronota`,`qdteitem`,`valoritem`)
VALUES('45','8','3','119.98');

INSERT INTO `itemnota`(`idproduto`,`numeronota`,`qdteitem`,`valoritem`)
VALUES('32','9','25','99.99');

INSERT INTO `itemnota`(`idproduto`,`numeronota`,`qdteitem`,`valoritem`)
VALUES('32','11','16','174.09');





















