CREATE DATABASE AULAS_UC3;
USE AULAS_UC3;

CREATE TABLE contato(
id INT AUTO_INCREMENT,
nome VARCHAR (150) NOT NULL,
email VARCHAR (150) NOT NULL,
telefone VARCHAR (150) NOT NULL,
PRIMARY KEY (id)
);

SELECT * FROM contato;
desc contato;